Reetan.Nayak Dev 25/force-app/main/default/objects/Weekly_Report__c/Weekly_Report__c.object-meta.xml
<CustomObject>
    <label>Weekly Report</label>
    <nameField>
        <displayFormat>WR-{YYYY}{MM}-{00000}</displayFormat>
        <label>Weekly Report #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weekly Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Weekly_Report__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <label>Report Date</label>
    <type>Date</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Weekly_Report_Data_Next_Week__c/Weekly_Report_Data_Next_Week__c.object-meta.xml
<CustomObject>
    <label>Next Week (My Activities)</label>
    <nameField>
        <displayFormat>WRDNW-{YYYY}{MM}-{00000}</displayFormat>
        <label>Weekly Report Data#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Next Week (My Activities)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Weekly_Report_Data_Next_Week__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Weekly_Report_Data_Next_Week</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Weekly_Report_Data_Next_Week__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Next_Week_My_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Weekly_Report_Data_Next_Week__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <label>Work Date</label>
    <type>Date</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Weekly_Report_Data_Next_Week__c/fields/Weekly_Report__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Report__c</fullName>
    <label>Weekly Report</label>
    <referenceTo>Weekly_Report__c</referenceTo>
    <relationshipName>Weekly_Report_Data_Next_Week</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Weekly_Report_Data_Next_Week__c/fields/Weekly_Report_Data_Next_Week__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Report_Data_Next_Week__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Weekly Report Data Next Week</label>
    <referenceTo>Weekly_Report_Data_Next_Week__c</referenceTo>
    <relationshipName>Weekly_Report_Data_Next_Week</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Weekly_Report_Data_This_Week__c/Weekly_Report_Data_This_Week__c.object-meta.xml
<CustomObject>
    <label>This Week (My Activities)</label>
    <nameField>
        <displayFormat>WRDTW-{YYYY}{MM}-{00000}</displayFormat>
        <label>Weekly Report Data#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>This Week (My Activities)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Weekly_Report_Data_This_Week__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Weekly_Report_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Weekly_Report_Data_This_Week__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>This_Week_My_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Weekly_Report_Data_This_Week__c/fields/Weekly_Report__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Report__c</fullName>
    <label>Weekly Report</label>
    <referenceTo>Weekly_Report__c</referenceTo>
    <relationshipName>Weekly_Report_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Weekly_Report_Data_This_Week__c/fields/Work_Information__c.field-meta.xml
<CustomField>
    <fullName>Work_Information__c</fullName>
    <label>Work Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/classes/WeekThisNextController.cls
/**
* @author Original: Reetan Nayak(502268483) Birlasoft/GEHC
* @date Original: 6th Feb 2014
* @description: This Class is used in component to return This Week and Next Week data in Email tempalate.
*/
public class WeekThisNextController {

    public Id WeeklyReportID { get; set; }
    
    public List<Weekly_Report_Data_This_Week__c> WRTW;
    public List<Weekly_Report_Data_Next_Week__c> WRNW;
    
    
    //To return List of This Week data in Email Template
    public list<Weekly_Report_Data_This_Week__c> getWRTW(){
        WRTW = [Select Id, Report_Date__c, Account__r.Name, Opportunity__r.Name, Task_Subject__c, Work_Information__c from Weekly_Report_Data_This_Week__c where Weekly_Report__c=:WeeklyReportID order by Report_Date__c];  
        return WRTW; 
    }
    
    //To return List of Next Week data in Email Template    
     public list<Weekly_Report_Data_Next_Week__c> getWRNW(){
        WRNW = [Select Id, Report_Date__c, Account__r.Name, Opportunity__r.Name, Task_Subject__c, Work_Information__c from Weekly_Report_Data_Next_Week__c where Weekly_Report__c=:WeeklyReportID  order by Report_Date__c];
        return WRNW; 
    }
    

}