Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Batchs</relationshipLabel>
    <relationshipName>Batchs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <label>Total Hours</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/fields/ProgramId__c.field-meta.xml
<CustomField>
    <fullName>ProgramId__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/Faculty__c.object-meta.xml
<CustomObject>
    <label>Faculty</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faculty</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Login_ID__c.field-meta.xml
<CustomField>
    <fullName>Login_ID__c</fullName>
    <label>Login ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>TA{00}</displayFormat>
        <label>Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Batch__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Session</relationshipLabel>
    <relationshipName>TestTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Duration_In_Hour__c.field-meta.xml
<CustomField>
    <fullName>Duration_In_Hour__c</fullName>
    <label>Duration In Hour</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12:00 AM</fullName>
            </value>
            <value>
                <fullName>12:30 AM</fullName>
            </value>
            <value>
                <fullName>1:00 AM</fullName>
            </value>
            <value>
                <fullName>1:30 AM</fullName>
            </value>
            <value>
                <fullName>2:00 AM</fullName>
            </value>
            <value>
                <fullName>2:30 AM</fullName>
            </value>
            <value>
                <fullName>3:00 AM</fullName>
            </value>
            <value>
                <fullName>3:30 AM</fullName>
            </value>
            <value>
                <fullName>4:00 AM</fullName>
            </value>
            <value>
                <fullName>4:30 AM</fullName>
            </value>
            <value>
                <fullName>5:00 AM</fullName>
            </value>
            <value>
                <fullName>5:30 AM</fullName>
            </value>
            <value>
                <fullName>6:00 AM</fullName>
            </value>
            <value>
                <fullName>6:30 AM</fullName>
            </value>
            <value>
                <fullName>7:00 AM</fullName>
            </value>
            <value>
                <fullName>7:30 AM</fullName>
            </value>
            <value>
                <fullName>8:00 AM</fullName>
            </value>
            <value>
                <fullName>8:30 AM</fullName>
            </value>
            <value>
                <fullName>9:00 AM</fullName>
            </value>
            <value>
                <fullName>9:30 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:30 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:30 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:30 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:30 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:30 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <label>Session Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Theory</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12:00 AM</fullName>
            </value>
            <value>
                <fullName>12:30 AM</fullName>
            </value>
            <value>
                <fullName>1:00 AM</fullName>
            </value>
            <value>
                <fullName>1:30 AM</fullName>
            </value>
            <value>
                <fullName>2:00 AM</fullName>
            </value>
            <value>
                <fullName>2:30 AM</fullName>
            </value>
            <value>
                <fullName>3:00 AM</fullName>
            </value>
            <value>
                <fullName>3:30 AM</fullName>
            </value>
            <value>
                <fullName>4:00 AM</fullName>
            </value>
            <value>
                <fullName>4:30 AM</fullName>
            </value>
            <value>
                <fullName>5:00 AM</fullName>
            </value>
            <value>
                <fullName>5:30 AM</fullName>
            </value>
            <value>
                <fullName>6:00 AM</fullName>
            </value>
            <value>
                <fullName>6:30 AM</fullName>
            </value>
            <value>
                <fullName>7:00 AM</fullName>
            </value>
            <value>
                <fullName>7:30 AM</fullName>
            </value>
            <value>
                <fullName>8:00 AM</fullName>
            </value>
            <value>
                <fullName>8:30 AM</fullName>
            </value>
            <value>
                <fullName>9:00 AM</fullName>
            </value>
            <value>
                <fullName>9:30 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:30 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:30 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:30 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:30 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:30 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/SessionEntry__c.object-meta.xml
<CustomObject>
    <label>SessionEntry</label>
    <nameField>
        <displayFormat>SE-{000}</displayFormat>
        <label>SessionEntry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Entry</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Batch__c</referenceTo>
    <relationshipLabel>Session Entry</relationshipLabel>
    <relationshipName>Session_Entry</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Session Entry</relationshipLabel>
    <relationshipName>Sessions_Entry</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Sessions Entry</relationshipLabel>
    <relationshipName>Sessions_Entry</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Session_Name__c.field-meta.xml
<CustomField>
    <fullName>Session_Name__c</fullName>
    <label>Session Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <label>Session Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Devlopement</fullName>
            </value>
            <value>
                <fullName>Theory</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
                <color>#FF0000</color>
                <label>Completed</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#419249</color>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Not yet Started</fullName>
                <color>#6633FF</color>
                <label>Not yet Started</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/classes/FactHomePageCorsBuidContr.cls
public class FactHomePageCorsBuidContr{

    public String selectValue{get;set;}
    public String seletedCors{get;set;}
    public String selectedbatch{get; set;} 
    public List<BatRec> batchDetails{get;set;}
    public String fid;
    public String facId;
    public List<SessionEntry__c> showSessionEntry{get;set;}
    public FactHomePageCorsBuidContr(){
        fid = ApexPages.currentPage().getParameters().get('Id');
        System.debug('.....fid................'+fid);
           try{
               faculty__c fac=[select Id,Name from faculty__c where Login_ID__c=:fid];
               facId=fac.Id;
           }catch(Exception e){}
    }

  public  List<SelectOption> getprogName(){
      List<SelectOption> option=new List<SelectOption>();
      try{
          List<Program__c> prg=[select Id,Name from Program__c];
          option.add(new SelectOption('','--select--'));
          for(Program__c p:prg){
              option.add(new SelectOption(p.Id,p.Name));
          }
      }catch(Exception e){} 
      return option; 
    }
  
    public List<SelectOption> getcorsList(){
        List<SelectOption> option=new List<SelectOption>();
        
        try{
          List<Course__C> crs=[select Id,Name from Course__c where ProgramId__c=:selectValue];
          for(Course__c c:crs){
              option.add(new SelectOption(c.Id,c.Name));
          }
        }catch(Exception e){}
        return option;
    }
    
    public List<SelectOption> getbatchList(){
        List<SelectOption> option=new List<SelectOption>();
        List<Batch__c> bat;
        if(selectValue != null){
            try{
                bat=[select Id,Name from Batch__c where CourseId__c=:seletedCors Limit 10];
            }catch(Exception e){}
            option.add(new SelectOption('','--select--'));
            option.add(new SelectOption('All Batches','All Batches'));
            for(Batch__c b:bat)
                option.add(new SelectOption(b.Id,b.Name));
       }
       return option;
    }
    
    public void readSessCors(){
        batchDetails=new List<BatRec>();
        try{
            Course__C crs=[select Id,Name from Course__c where Id=:seletedCors Limit 1];
            List<SessionEntry__c> ssentList=[SELECT Id,Faculty__c, Batch__c,  Session_Type__c, Session__c, Status__c, Session_Name__c, Course_Name__c, 
                             Start_Time__c, End_Time__c from sessionentry__c where Course_Name__c=:crs.Name ];
            System.debug('The course name is------------------'+seletedCors);
                             
            List<Batch__c> batList;
            if(selectedbatch == 'All Batches'){                     
                batList=[select Id,Name,Start_Time__c,End_Time__c,Start_Date__c,Total_Hours__c from Batch__c where CourseId__c=:seletedCors  order by Name Asc  Limit 10  ];
            }else{
                batList=[select Id,Name,Total_Hours__c,Start_Time__c,End_Time__c,Start_Date__c from Batch__c where CourseId__c=:seletedCors and Id=:selectedbatch   Limit 1  ];
            }
            List<Session__c> ssList=[Select Id,Name,Session_Name__c,Session_Type__c,Duration_In_Hour__c from Session__c where CourseId__c=:seletedCors  limit 50];
            
            if(selectedbatch != null && batList.size()>0){
                Map<String,List<SessionEntry__c>> batchSessionMap =new  Map<String,List<SessionEntry__c>>();
                for(SessionEntry__c ssent:ssentList){
                    List<SessionEntry__c> sestemp = batchSessionMap.get(ssent.batch__c);
                    if(sestemp == null){
                        sestemp = new List<SessionEntry__c>();
                        sestemp.add(ssent);
                        batchSessionMap.put(ssent.batch__c,sestemp);
                    }else{
                        sestemp.add(ssent);
                    }
                }
                
                for(Batch__c b:batList){ 
                    Boolean isBatch = false;
                    Integer count=0;
                    for(String key : batchSessionMap.keyset()){
                        if(b.Id == key){
                            isBatch=true;
                            List<SessionEntry__c> sList = batchSessionMap.get(key);
                            System.debug('--------------------+++++++++'+key);
                            BatRec br = new BatRec();
                            br.bname = b.Name;
                            br.bid = b.id;
                            br.sDate=b.Start_Date__c;
                            br.sTime=b.Start_Time__c;
                            br.eTime=b.End_Time__c;
                            br.session = new List<SecRec>();
                            for(Session__c sc :ssList){
                                boolean isSel = false;
                                for(SessionEntry__c sce : sList){
                                    if(sc.Session_Name__c == sce.Session_Name__c && sc.Session_Type__c == sce.Session_Type__c && sce.faculty__c == null){
                                        isSel = true;
                                        count+=1;
                                        break;
                                    }
                                }
                                if(isSel){
                                    br.session.add(new SecRec(sc));
                                }
                            }
                            if(count == 0)
                                br.showSection=false;
                            batchDetails.add(br);
                        } 
                    }
                    if(!isbatch){
                        BatRec br = new BatRec();
                        br.bname = b.Name;
                        br.bId=b.Id;
                        br.sDate=b.Start_Date__c;
                        br.sTime=b.Start_Time__c;
                        br.eTime=b.End_Time__c;
                        List<SecRec> srecList = new List<SecRec>();
                        for(Session__c sc:ssList)
                            srecList.add(new SecRec(sc));
                        br.session = srecList;
                        batchDetails.add(br);
                    }
                } 
            }
        }catch(Exception e){}  
    } 
    
    public void showSessEntry(){
        showSessionEntry=new List<SessionEntry__c>();
        try{     
            Course__C crs=[select Id,Name from Course__c where Id=:seletedCors Limit 1]; 
            List<SessionEntry__c> ssEntryList=[SELECT Id,Faculty__c, Batch__c,  Session_Type__c, Session__c, Status__c, Session_Name__c, Course_Name__c, 
                                                Start_Time__c, End_Time__c  from sessionentry__c where Course_Name__c=:crs.Name AND Faculty__c != null order by Batch__c desc Limit 30 ];  
                          
            for(SessionEntry__c ss: ssEntryList)                                  
            showSessionEntry.add(new SessionEntry__c(Faculty__c=ss.Faculty__c,Batch__c=ss.Batch__c,Session_Name__c=ss.Session_Name__c,Session_Type__c=ss.Session_Type__c,Start_Time__c=ss.Start_Time__c,
                                                     End_Time__c=ss.End_Time__c,Course_Name__c=ss.Course_Name__c));   
        }catch(Exception e){} 
        readSessCors();  
    } 
     
     public PageReference saveSessionEntry() {
         
         try{
             Course__C crs=[select Id,Name from Course__c where Id=:seletedCors Limit 1]; 
             List<SessionEntry__c> sentryList=[SELECT Id,Name,Faculty__c, Batch__c,  Session_Type__c, Session__c, Status__c, Session_Name__c, Course_Name__c, 
                                                    Start_Time__c, End_Time__c  from sessionentry__c where Course_Name__c=:crs.Name order by Batch__c desc Limit 30 ];
             Double totalTime=0;
             Faculty__c fac=[Select Id,Name from Faculty__c where Id=:facId limit 1];
             for(SessionEntry__c ssent:sentryList){
                 for(BatRec b:batchDetails){
                     Integer count=0;
                     for(SecRec s: b.session){
                         System.debug('The selected values are....................'+s.isSelected);
                         if(s.isSelected == true && b.bid==ssent.Batch__c && s.sec.Session_Name__c == ssent.Session_Name__c && s.sec.Session_Type__c == ssent.Session_Type__c && ssent.faculty__c == null){
                             count += 1;
                             ssent.faculty__c = facId;
                             ssent.Status__c='In Progress';
                         }
                     }
                     if(count > 0){
                         Batch__c bat=[Select Id,Name,Status__c from Batch__c where Id=:b.bId Limit 1 ];
                         bat.Status__c='In Progress';
                         update bat;
                     }
                 }  
             }
             upsert sentryList;
             showSessEntry();
             readSessCors();
         }catch(Exception e){}
         
         return null;
    } 
 
    public class BatRec{
        public String Selected;
        public Boolean showSection{get;set;} 
        public Id bid{get;set;}
        public Date sDate{get;set;}
        public String stime{get;set;}
        public String etime{get;set;}
        public String bname{get;set;}
        public List<SecRec> session{get;set;}
        public BatRec(){
            showSection=true;
        }   
   }
    
   public class SecRec{
       public Boolean isSelected{get;set;} 
       public Session__c sec {get;set;}
       public SecRec(Session__c nsec){
              isSelected = false;
              sec = nsec;
       } 
   }
   
   //Test Methods
   static testMethod void testFacCrsBld(){
        faculty__c fac=new faculty__c();
        fac.Name='Raju';
        fac.Last_Name__c='Shewad';
        fac.DOB__c=System.toDay();
        fac.Email_ID__c='baruna@ceptes.com';
        fac.Mobile_No__c='2121343456';
        fac.PIN__c=232323;
        Insert fac;
        
        Program__c prg=new Program__c();
        prg.Name='DWH';
        Insert prg;
        
        Course__c crs=new Course__c();
        crs.Name='J2ME';
        crs.ProgramId__c=prg.Id;
        Insert crs;
        
        Session__c ssn = new Session__c();
        ssn.CourseId__c = crs.Id;
        ssn.Session_Name__c = 'intro';
        ssn.Session_Type__c = 'Theory';
        ssn.Duration_In_Hour__c = 3;
        insert ssn;
        
        Batch__c bat=new Batch__c();
        bat.CourseId__c=crs.Id;
        bat.Name='Morning';
        bat.Start_Time__c='10:00AM';
        bat.End_Time__c='12:30PM';
        bat.Start_Date__c=System.toDay();
        bat.Session_Det__c ='Only Weekend';
        insert bat;
        
        SessionEntry__c ses= new SessionEntry__c();
        ses.Session_Name__c='Intr';
        ses.Session_Type__c='Devlopment';
        ses.Course_Name__c=crs.Name;
        ses.Start_Time__c='10:00AM';
        ses.End_Time__c='12:00PM';
        ses.faculty__c=fac.Id;
        ses.Batch__c=bat.Id;
        insert ses; 
        
        faculty__c fa=[select Id,Name,Login_ID__c from faculty__c where Name='Raju'];
        
        FactHomePageCorsBuidContr factcrs=new FactHomePageCorsBuidContr();
        ApexPages.currentPage().getParameters().put('Id',fa.Login_ID__c);
        factcrs.facId=fa.Id;
        factcrs.selectValue=prg.Id;
        factcrs.seletedCors=crs.Id;
        factcrs.selectedbatch=bat.Id;
        factcrs.getprogName();
        factcrs.getcorsList();
        factcrs.getbatchList();
        factcrs.readSessCors();
        factcrs.showSessEntry();
        factcrs.saveSessionEntry();
        Delete fac;
        Delete bat;
        
    }
    static  testMethod void studentTestTrigger1(){
     Program__c prg=new Program__c();
        prg.Name='ABCD';
        insert prg;
        
        Course__c crs=new Course__c();
        crs.Name='ABC';
        crs.ProgramId__c=prg.Id;
        insert crs;
        
        Batch__c bat=new Batch__c();
        bat.CourseId__c=crs.Id;
        bat.Name='Morning';
        bat.Start_Time__c='08:30AM';
        bat.End_Time__c='10:30AM';
        bat.Start_Date__c=System.toDay();
        bat.Session_Det__c ='Exclude Weekend';
        insert bat;    
    } 
}