Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/Faculty__c.object-meta.xml
<CustomObject>
    <label>Faculty</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faculty</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Email_ID__c</fullName>
    <externalId>true</externalId>
    <label>Email ID</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Login_ID__c.field-meta.xml
<CustomField>
    <fullName>Login_ID__c</fullName>
    <label>Login ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/SessionEntry__c.object-meta.xml
<CustomObject>
    <label>SessionEntry</label>
    <nameField>
        <displayFormat>SE-{000}</displayFormat>
        <label>SessionEntry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Entry</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Batch__c</referenceTo>
    <relationshipLabel>Session Entry</relationshipLabel>
    <relationshipName>Session_Entry</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Session Entry</relationshipLabel>
    <relationshipName>Sessions_Entry</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/classes/FacultySessEntryContr.cls
public class FacultySessEntryContr {

public String fid;
public String selectCourse {get; set;}
public SessionEntry__c SesEnt {get; set;}
public Batch__c batDate{get;set;}

    public FacultySessEntryContr() {
        SesEnt = new SessionEntry__c();
        fid = ApexPages.currentPage().getParameters().get('Id'); 
        System.debug('>>>>>>>>. Chk the FID >>>>>>. ' + fid);
        }

    public List<SelectOption> getCourseList() {
        List<SelectOption> lst = new List<SelectOption>();
        lst.add(new SelectOption('', '--Select--'));
        
        List<Course__c> crs = [Select Id, Name from Course__c order by Name];
            for(Course__c c:crs){
                lst.add(new SelectOption(c.Name, c.Name));
            }
            return lst;
        }
     
     public void doSave() {
        try{    
            Faculty__c fact = [select Id, Name, Login_ID__c from Faculty__c where Login_ID__c=:fid];
            // Faculty__c fact = [select Id, Name from Faculty__c where Id='a0790000002MJKjAAO'];
            SesEnt.Faculty__c = fact.Id;
            SesEnt.Course_Name__c = selectCourse;
            
            insert this.SesEnt;
            System.debug('Chk the Inserted...... '+ this.SesEnt);
          } catch(Exception e) {}
         this.SesEnt = null;
     }   
    
    static testMethod void SEntryTest(){
        faculty__c fac=new faculty__c();
        fac.Name='Raju';
        fac.Last_Name__c='Shewad';
        fac.DOB__c=System.toDay();
        fac.Email_ID__c='baruna@ceptes.com';
        fac.Mobile_No__c='2121343456';
        fac.PIN__c=232323;
        Insert fac;
        
        faculty__c fa=[select Id,Name,Login_ID__c from faculty__c where Name='Raju'];
        ApexPages.currentPage().getParameters().put('Id',fa.Login_ID__c);
        FacultySessEntryContr facses=new FacultySessEntryContr();
        facses.getCourseList();
        facses.doSave();
        
        Delete fac;
        
    }
    
}