Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/BatchId__c.field-meta.xml
<CustomField>
    <fullName>BatchId__c</fullName>
    <displayFormat>B{00}</displayFormat>
    <label>BatchId</label>
    <type>AutoNumber</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Batchs</relationshipLabel>
    <relationshipName>Batchs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/fields/Course_Fees__c.field-meta.xml
<CustomField>
    <fullName>Course_Fees__c</fullName>
    <label>Course Fees</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/fields/Programs__c.field-meta.xml
<CustomField>
    <fullName>Programs__c</fullName>
    <label>Programs</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core Java</fullName>
            </value>
            <value>
                <fullName>JSP</fullName>
            </value>
            <value>
                <fullName>Servlets</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>Struts</fullName>
            </value>
            <value>
                <fullName>VisualForce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/Faculty__c.object-meta.xml
<CustomObject>
    <label>Faculty</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faculty</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Programs__c.field-meta.xml
<CustomField>
    <fullName>Programs__c</fullName>
    <label>Programs</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Courses__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>APEX</fullName>
            </value>
            <value>
                <fullName>Asp.NET</fullName>
            </value>
            <value>
                <fullName>C#.NET</fullName>
            </value>
            <value>
                <fullName>Core Java</fullName>
            </value>
            <value>
                <fullName>JSP</fullName>
            </value>
            <value>
                <fullName>Oracle- 9i</fullName>
            </value>
            <value>
                <fullName>PLSQL</fullName>
            </value>
            <value>
                <fullName>RUBY</fullName>
            </value>
            <value>
                <fullName>Servlets</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>SQL</fullName>
            </value>
            <value>
                <fullName>Struts</fullName>
            </value>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>VB.NET</fullName>
            </value>
            <value>
                <fullName>VisualForce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>TA{00}</displayFormat>
        <label>Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Batch__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Session</relationshipLabel>
    <relationshipName>TestTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <label>Session Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Theory</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/SessionEntry__c.object-meta.xml
<CustomObject>
    <label>SessionEntry</label>
    <nameField>
        <displayFormat>SE-{000}</displayFormat>
        <label>SessionEntry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Entry</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Batch__c</referenceTo>
    <relationshipLabel>Session Entry</relationshipLabel>
    <relationshipName>Session_Entry</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Session Entry</relationshipLabel>
    <relationshipName>Sessions_Entry</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Sessions Entry</relationshipLabel>
    <relationshipName>Sessions_Entry</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Session_Name__c.field-meta.xml
<CustomField>
    <fullName>Session_Name__c</fullName>
    <label>Session Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <label>Session Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Devlopement</fullName>
            </value>
            <value>
                <fullName>Theory</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
                <color>#FF0000</color>
                <label>Completed</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#419249</color>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Not yet Started</fullName>
                <color>#6633FF</color>
                <label>Not yet Started</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Student__c/fields/BatchId__c.field-meta.xml
<CustomField>
    <fullName>BatchId__c</fullName>
    <label>BatchId</label>
    <referenceTo>Batch__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Student__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CourseId</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Student__c/fields/loginId__c.field-meta.xml
<CustomField>
    <fullName>loginId__c</fullName>
    <label>loginId</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Student__c/fields/SEmail_Id__c.field-meta.xml
<CustomField>
    <fullName>SEmail_Id__c</fullName>
    <label>SEmail Id</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Student__c/fields/St_Mob_No__c.field-meta.xml
<CustomField>
    <fullName>St_Mob_No__c</fullName>
    <label>St Mob No</label>
    <type>Phone</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <label>Test</label>
    <nameField>
        <displayFormat>T{000}</displayFormat>
        <label>TestId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Test__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <label>Faculty</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bishnu</fullName>
            </value>
            <value>
                <fullName>Manoj</fullName>
            </value>
            <value>
                <fullName>Baruna</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/classes/StudentController.cls
Public class StudentController{
    public boolean displayPopup {get; set;}
    public String sid;
    public StudentController() {
        sid=ApexPages.currentPage().getParameters().get('id');
        System.debug('...............................'+sid);
    }
    
    public PageReference cancelButton(){
        PageReference ref=new PageReference('null');
        ref.setRedirect(true);
        return ref;
    }
    public PageReference doExam() {
        PageReference pgref=new PageReference('/apex/Dev401Exam');
        pgref.setRedirect(true);
        return pgref;
    }
    
    public PageReference doLogout(){
        PageReference pgref=new PageReference('/apex/loginpage');
        pgref.setRedirect(true);
        return pgref;
    }
    
        
    public Student__c[] getName(){
        Student__c[] student;
        try{
          student=[Select Name,Last_Name__c, St_Mob_No__c, SEmail_Id__c,loginId__c from Student__c where loginId__c=:sid];
        }catch(Exception e){}
        return student;
    }
    public List<Course__c> getCourse(){
        List<Course__c> csp =new List<Course__c>();
        try{
            Student__c stt1=[select id,BatchId__c from Student__c where loginId__c=:sid];
            Batch__c bat=[SELECT Id, CourseId__c from batch__c where id=:stt1.BatchId__c];
            
            System.debug('..........batchid is..'+bat);
            csp=[SELECT Id,Course_Fees__c, Course_Name__c, Programs__c from Course__c where id=:bat.CourseId__c];
        }catch(Exception e){}
        return csp;
    }
    
    public List<sessionentry__c> getTask(){
    
        List<sessionentry__c> session;
        try{
            List<Student__c> stt1=new List<Student__c>();
            stt1=[select id,BatchId__c from Student__c where loginId__c=:sid];
            List<Batch__c> bat=new List<Batch__c>();
            bat=[SELECT Id, CourseId__c from batch__c where id=:stt1[0].BatchId__c];
             //System.debug('.................'+bat[0].CourseId__c);
            session=[SELECT Id,  Faculty__c, Batch__c, Comment__c, Session_Type__c, Session__c, Status__c, Session_Name__c, Course_Name__c, Start_Time__c, End_Time__c, 
                    selectsesion__c, New_Task__c, No_Of_Hours__c from sessionentry__c where batch__c =:bat[0].id and Status__c='Completed'];
        }catch(Exception e){}
        return session;
        
    }
    public List<sessionentry__c>getTopicInProgress(){
        List<sessionentry__c> session;
        try{
            List<Student__c> stt1=new List<Student__c>();
            stt1=[select id,BatchId__c from Student__c where loginId__c=:sid];
            List<Batch__c> bat=new List<Batch__c>();
            bat=[SELECT Id,Name, CourseId__c from batch__c where id=:stt1[0].BatchId__c];
            System.debug('...................batch name......'+bat[0].Name);
            session=[SELECT Id,  Faculty__c, Batch__c, Comment__c, Session_Type__c, Session__c, Status__c, Session_Name__c, Course_Name__c, Start_Time__c, End_Time__c,
                     selectsesion__c, New_Task__c, No_Of_Hours__c from sessionentry__c where batch__c =:bat[0].id and Status__c='In Progress'];
        }catch(Exception e){
             System.debug(e);
        }
        return session;
    
    }
        
    public List<sessionentry__c> getTopicNotStarted(){    
        List<sessionentry__c> session;
        try{
            List<Student__c> stt1=new List<Student__c>();
            stt1=[select id,BatchId__c from Student__c where loginId__c=:sid];
            List<Batch__c> bat=new List<Batch__c>();
            bat=[SELECT Id, CourseId__c from batch__c where id=:stt1[0].BatchId__c];
            session=[SELECT Id,  Faculty__c, Batch__c, Comment__c, Session_Type__c, Session__c, Status__c, Session_Name__c, Course_Name__c, Start_Time__c, End_Time__c, 
                    selectsesion__c, New_Task__c, No_Of_Hours__c from sessionentry__c where batch__c =:bat[0].id and Status__c='Not Started'];
        }catch(Exception e){
            System.debug(e);
          }
         return session;
    }        
            
    public List<Test__c> getTest(){
        List<Test__c> test;
        try{
           Student__c stt1=new Student__c();
            List<Batch__c> bat=new List<Batch__c>();
            List<Session__c> ses=new List<Session__c>();
            stt1=[select id,BatchId__c from Student__c where loginId__c=:sid];
            bat=[SELECT Id, CourseId__c from batch__c where id=:stt1.BatchId__c]; 
            ses=[SELECT Id, CourseId__c, batch__c,Status__c from session__c where batch__c=:bat[0].id and Status__c='Completed'];  
            test=[SELECT Id, Faculty__c, TaskId__c, Test_Name__c,TestPendingStatus__c, Test_Status__c, Test_Approval__c,
            Assignment_Approval__c from test__c where TaskId__c=:ses[0].id];
        }catch(Exception e){
            System.debug('inside test '+e);
        }
        return test;
    }   
          
    public void closePopup() {        
        displayPopup = false; 
    }     
    public void showPopup() {        
        displayPopup = true;    
    }
    public PageReference doTest(){
        PageReference pgref=new PageReference('/apex/Dev401Exam?id='+sid);
        pgref.setRedirect(true);
        return pgref;
    }
                
    //test method here

    static testMethod void studentTest(){
        ApexPages.currentPage().getParameters().put('id','assw0');
        String sid=ApexPages.currentPage().getParameters().get('id');
        StudentController stc=new StudentController();
        stc.doLogout();
        stc.doTest();
        stc.doExam();
        stc.getName();
        stc.getCourse();
        stc.getTask();
        stc.getTest();
        stc.getTopicInProgress();
        stc.getTopicNotStarted();
        //  stc.getTest();
        stc.cancelButton();
        stc.closePopup();
        stc.showPopup();
    }
    
     static testMethod void studentTestWithout(){
        StudentController stc=new StudentController();
        ApexPages.currentPage().getParameters().put('id','null');
        String sid=ApexPages.currentPage().getParameters().get('id');
        stc.getName();
        stc.getCourse();
        stc.getTask();
        stc.getTopicInProgress();
        stc.getTopicNotStarted();
        //stc.getTest();
     }
    
}