Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Batchs</relationshipLabel>
    <relationshipName>Batchs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/fields/Course_Duration__c.field-meta.xml
<CustomField>
    <fullName>Course_Duration__c</fullName>
    <label>Course Duration in hr</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/fields/Course_Fees__c.field-meta.xml
<CustomField>
    <fullName>Course_Fees__c</fullName>
    <label>Course Fees</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/fields/ProgramId__c.field-meta.xml
<CustomField>
    <fullName>ProgramId__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/fields/Programs__c.field-meta.xml
<CustomField>
    <fullName>Programs__c</fullName>
    <label>Programs</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core Java</fullName>
            </value>
            <value>
                <fullName>JSP</fullName>
            </value>
            <value>
                <fullName>Servlets</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>Struts</fullName>
            </value>
            <value>
                <fullName>VisualForce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>TA{00}</displayFormat>
        <label>Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Batch__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Session</relationshipLabel>
    <relationshipName>TestTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Duration_In_Hour__c.field-meta.xml
<CustomField>
    <fullName>Duration_In_Hour__c</fullName>
    <label>Duration In Hour</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12:00 AM</fullName>
            </value>
            <value>
                <fullName>12:30 AM</fullName>
            </value>
            <value>
                <fullName>1:00 AM</fullName>
            </value>
            <value>
                <fullName>1:30 AM</fullName>
            </value>
            <value>
                <fullName>2:00 AM</fullName>
            </value>
            <value>
                <fullName>2:30 AM</fullName>
            </value>
            <value>
                <fullName>3:00 AM</fullName>
            </value>
            <value>
                <fullName>3:30 AM</fullName>
            </value>
            <value>
                <fullName>4:00 AM</fullName>
            </value>
            <value>
                <fullName>4:30 AM</fullName>
            </value>
            <value>
                <fullName>5:00 AM</fullName>
            </value>
            <value>
                <fullName>5:30 AM</fullName>
            </value>
            <value>
                <fullName>6:00 AM</fullName>
            </value>
            <value>
                <fullName>6:30 AM</fullName>
            </value>
            <value>
                <fullName>7:00 AM</fullName>
            </value>
            <value>
                <fullName>7:30 AM</fullName>
            </value>
            <value>
                <fullName>8:00 AM</fullName>
            </value>
            <value>
                <fullName>8:30 AM</fullName>
            </value>
            <value>
                <fullName>9:00 AM</fullName>
            </value>
            <value>
                <fullName>9:30 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:30 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:30 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:30 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:30 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:30 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/FacultyID__c.field-meta.xml
<CustomField>
    <fullName>FacultyID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Session_Status__c.field-meta.xml
<CustomField>
    <fullName>Session_Status__c</fullName>
    <label>Session Status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <label>Session Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Theory</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12:00 AM</fullName>
            </value>
            <value>
                <fullName>12:30 AM</fullName>
            </value>
            <value>
                <fullName>1:00 AM</fullName>
            </value>
            <value>
                <fullName>1:30 AM</fullName>
            </value>
            <value>
                <fullName>2:00 AM</fullName>
            </value>
            <value>
                <fullName>2:30 AM</fullName>
            </value>
            <value>
                <fullName>3:00 AM</fullName>
            </value>
            <value>
                <fullName>3:30 AM</fullName>
            </value>
            <value>
                <fullName>4:00 AM</fullName>
            </value>
            <value>
                <fullName>4:30 AM</fullName>
            </value>
            <value>
                <fullName>5:00 AM</fullName>
            </value>
            <value>
                <fullName>5:30 AM</fullName>
            </value>
            <value>
                <fullName>6:00 AM</fullName>
            </value>
            <value>
                <fullName>6:30 AM</fullName>
            </value>
            <value>
                <fullName>7:00 AM</fullName>
            </value>
            <value>
                <fullName>7:30 AM</fullName>
            </value>
            <value>
                <fullName>8:00 AM</fullName>
            </value>
            <value>
                <fullName>8:30 AM</fullName>
            </value>
            <value>
                <fullName>9:00 AM</fullName>
            </value>
            <value>
                <fullName>9:30 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:30 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:30 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:30 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:30 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:30 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <label>Task</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex Class And Testmethod</fullName>
            </value>
            <value>
                <fullName>Apex trigger</fullName>
            </value>
            <value>
                <fullName>WebServices</fullName>
            </value>
            <value>
                <fullName>Standard And Custom Object</fullName>
            </value>
            <value>
                <fullName>Visualforce Page</fullName>
            </value>
            <value>
                <fullName>Action Class</fullName>
            </value>
            <value>
                <fullName>Struts Tile frmework</fullName>
            </value>
            <value>
                <fullName>JSF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Task_Completed__c.field-meta.xml
<CustomField>
    <fullName>Task_Completed__c</fullName>
    <label>Task Completed</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Test_Status__c.field-meta.xml
<CustomField>
    <fullName>Test_Status__c</fullName>
    <label>Test Status</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Topic_Covered__c.field-meta.xml
<CustomField>
    <fullName>Topic_Covered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Topic Covered</label>
    <type>Checkbox</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Topic_InProgress__c.field-meta.xml
<CustomField>
    <fullName>Topic_InProgress__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Topic InProgress</label>
    <type>Checkbox</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Topic_Not_Yet_Started__c.field-meta.xml
<CustomField>
    <fullName>Topic_Not_Yet_Started__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Topic Not Yet Started</label>
    <type>Checkbox</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/classes/CoHomePageCourTabContlr.cls
public class CoHomePageCourTabContlr {

    public List<Course__c> selectCors { get; set;}
    public List<Course__c> selectCourse { get; set;}
    public List<Session__c> selectsess{get;set;}
    public Course__c cours { get; set;}
    public Boolean courseDetails1{get;set;}
    public Boolean courseDetails2{get;set;}
    public Boolean showcourse{get;set;} 
    public Boolean showSession{get;set;} 
    public String courseId {get; set;}
    public Boolean isError{get;set;}
    public Integer selectPage {get; set;}
    private final Course__c cors;  
    public String errorMessage{get;set;}
  
    
    public CoHomePageCourTabContlr() {               
        this.courseDetails1=false;
        this.cours = new Course__c();
        this.selectCors = (List<Course__c>) courseRecords.getRecords();
    }   

    public CoHomePageCourTabContlr(ApexPages.StandardSetController controller) {
       this.cors = (Course__c)controller.getRecord(); 
    }        
    
    
    public ApexPages.StandardSetController courseRecords {
        get {
            if(courseRecords == null) {
                courseRecords = new ApexPages.StandardSetController(Database.getQueryLocator( [SELECT Id,  Name,  Programs__c,  Course_Name__c, ProgramId__c from Course__c  order by ProgramId__c ]));
                System.debug('courseRecords.setPageSize' + courseRecords.getResultSize());
               
                courseRecords.setPageSize(6);
                courseRecords.setpageNumber(0);
                }
            return courseRecords;
        }
        set;
    }        
    
    
    public void nextButton() {
        courseRecords.next();
        this.selectCors = (List<Course__c>) courseRecords.getRecords();
        }

    public void previousButton() {
        courseRecords.previous();
        this.selectCors = (List<Course__c>) courseRecords.getRecords();
        }    

    public void firstButton() {
        courseRecords.first();
        this.selectCors = (List<Course__c>) courseRecords.getRecords();
        }    

    public void lastButton() {
        courseRecords.last();
        this.selectCors = (List<Course__c>) courseRecords.getRecords();
        }    

    public Integer getPageNo(){
        return courseRecords.getPageNumber();
    }
    
    public List<Integer> getPageNos(){
        List<Integer> lst = new List<Integer>();
          for(Integer i=1; i<=getTotalPageNumber(); i++) {
            lst.add(i);
        }
        return lst;
    }
       
    public Integer getTotalPageNumber(){
        Integer n = getTotalRecords() - (getPageSize() * (getTotalRecords() / getPageSize()));
         if(n == 0){
             return getTotalRecords() / getPageSize();
             }
         else
         return (getTotalRecords() / getPageSize()) + 1;
    }
    
    public Integer getPageSize(){
        return courseRecords.getPageSize();
    }       
    
    public Integer getTotalRecords(){        
        return courseRecords.getResultSize();
    }
 
    public Boolean getDisableNext(){
        return courseRecords.getHasNext();
    }
    
    public Boolean getDisablePrevious(){
        return courseRecords.getHasPrevious();
    }
    
    public void onClickPageNo() {
        System.debug('selectPage.......' + selectPage);
        courseRecords.setpageNumber(selectPage);
        this.selectCors = (List<Course__c>) courseRecords.getRecords();
     }        
     
     public void doNewCourse() {
        cours=new Course__c();
        this.selectsess = null;
        courseDetails1=true;
        courseDetails2=true;
        showSession=false;
        showcourse=false;
        isError=false;
        
       
    }


    public void addNewSession() {
     if(selectsess == null || selectsess.size() == 0){
         selectsess = new List<Session__c>();
         selectsess.add(new Session__c());
         courseDetails1=true;
         courseDetails2=true;
         showSession=true;
     }else{
          selectsess.add(new Session__c());
          
     }
    }
    
    public void saveCourse(){
        if(selectsess == null || selectsess.size() == 0){
            isError=true;
            errorMessage='At least one session should be inside course';
         }else{    
             try{
                 Decimal Totalhour=0;
                 for(Session__c sess : selectsess)
                     Totalhour=Totalhour+sess.Duration_In_Hour__c;    
                                  
                 cours.Course_Duration__c=Totalhour;
                 upsert cours;
                 for(Session__c sess : selectsess)
                     sess.CourseId__c = cours.Id;
                 
                 upsert selectsess;
                 courseRecords = null;
                 this.selectCors=[SELECT Id, Name, CreatedDate,ProgramId__c, Course_Duration__c, Course_Fees__c, Course_Name__c, Programs__c from course__C];
                 
             }catch(Exception e){
                 System.debug('Error ---- '+e);
             }
               courseDetails1=false;
       }        
    }
    
     
    public List<SelectOption> getfieldValues(){
        List<SelectOption> fieldValues = new List<SelectOption>();
        Schema.DescribeFieldResult evntField = Schema.sObjectType.Session__c.fields.Session_Type__c;
        Schema.PicklistEntry [] values = evntField.getPickListValues();
        for(Schema.PicklistEntry val : values){
            fieldValues.add(new SelectOption(val.getValue(), val.getLabel()));
        }
        return fieldValues;
    } 
     
    public void deleteCourseRecords(){
         try{
             Course__c cors=[SELECT Id, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById,
                             SystemModstamp, ProgramId__c, Course_Duration__c, Course_Fees__c, Course_Name__c, Programs__c 
                             from course__c where Id=:courseId LIMIT 1];
             
             List<Session__c> sess=[SELECT Id,  IsDeleted, Name,Duration_In_Hour__c, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById,
                         SystemModstamp, CourseId__c, FacultyID__c, Batch__c, Comment__c, Date__c, End_Time__c, Session_Status__c,
                         Session_Type__c, Start_Time__c, Status__c, Task_Completed__c, Task__c, Test_Status__c, Topic_Covered__c, 
                         Topic_InProgress__c, Topic_Not_Yet_Started__c,Session_Name__c from session__C
                         where CourseId__c=:courseId];
             System.debug('.........................................'+selectsess);           
             delete sess; 
             delete cors;            
             courseRecords = null;
             this.selectCors = (List<Course__c>) courseRecords.getRecords();        
         }catch(Exception e) {}
            courseDetails1=false;
    }  
    
    public void deleteSession(){
        try{
            Session__c ses=[SELECT Id, IsDeleted, Name,Duration_In_Hour__c, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById,
                            SystemModstamp, CourseId__c, FacultyID__c, Batch__c, Comment__c, Date__c, End_Time__c, Session_Status__c,
                            Session_Type__c, Start_Time__c, Status__c, Task_Completed__c, Task__c, Test_Status__c, Topic_Covered__c,
                            Topic_InProgress__c, Topic_Not_Yet_Started__c,Session_Name__c from session__c
                            where Id=:courseId];
           delete ses;
           Course__c crs=[select Id,Name from Course__c where Id=:ses.CourseId__c];  
           this.selectsess=[select Id,Session_Name__c,Duration_In_Hour__c,Session_Type__c from Session__c where CourseId__c=:crs.Id];                
              
       }catch(Exception e){}
    }
    
    public void editCoursreDetails(){
        try{
            cours=[SELECT Id, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, 
                         ProgramId__c, Course_Duration__c, Course_Fees__c, Course_Name__c, Programs__c from course__c where Id=:courseId];
            selectsess=[select Id,Session_Name__c,Duration_In_Hour__c,Session_Type__c from Session__c where CourseId__c=:courseId];             
        }catch(Exception e){}    
            courseDetails1=true;
            courseDetails2=true;
            showcourse=false;
            showSession=true;
        
    }   
  
   public void showSessionDetails(){
       try{
           selectCourse=[SELECT Id, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, 
                         ProgramId__c, Course_Duration__c, Course_Fees__c, Course_Name__c, Programs__c from course__c where Id=:courseId];
           selectsess=[select Id,Session_Name__c,Duration_In_Hour__c,Session_Type__c from Session__c where CourseId__c=:courseId];
           System.debug('I m inside session================'+selectsess);
       }catch(Exception e){}
       courseDetails1=true;
       courseDetails2=false;
       showSession=false;
       showcourse=true; 
   }  
   
   public void courseDetails1(){
       this.courseDetails1=false;
   } 
   
   //Test Method
   static testMethod void TestCourse() {
    
            Program__c prg=new Program__c();
            prg.Name='DWH';
            Insert prg;
           
            Course__c crs=new Course__c();
            crs.Name='J2ME';
            crs.ProgramId__c=prg.Id;
            Insert crs;
                 
            Session__c ssn = new Session__c();
            ssn.CourseId__c = crs.Id;
            ssn.Session_Name__c = 'intro';
            ssn.Session_Type__c = 'Theory';
            ssn.Duration_In_Hour__c = 3;
            insert ssn;
    
        CoHomePageCourTabContlr cordCourTab = new CoHomePageCourTabContlr();
            cordCourTab.courseId=crs.Id;
            cordCourTab.nextButton();
            cordCourTab.previousButton();
            cordCourTab.firstButton();
            cordCourTab.lastButton();
            cordCourTab.getPageNo();
            cordCourTab.getPageNos();
            cordCourTab.getDisableNext();
            cordCourTab.getDisablePrevious();
            cordCourTab.selectPage = 6;
            cordCourTab.onClickPageNo();
            cordCourTab.doNewCourse();
            cordCourTab.addNewSession();
            cordCourTab.saveCourse();
            cordCourTab.getfieldValues();
            cordCourTab.deleteCourseRecords();
            cordCourTab.deleteSession();
            cordCourTab.editCoursreDetails();
            cordCourTab.showSessionDetails();
            cordCourTab.courseDetails1();
    
    }
   
}