Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Batchs</relationshipLabel>
    <relationshipName>Batchs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/Faculty__c.object-meta.xml
<CustomObject>
    <label>Faculty</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faculty</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Courses__c.field-meta.xml
<CustomField>
    <fullName>Courses__c</fullName>
    <label>Courses</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Force</fullName>
            </value>
            <value>
                <fullName>JAVA</fullName>
            </value>
            <value>
                <fullName>.NET</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Email_ID__c</fullName>
    <externalId>true</externalId>
    <label>Email ID</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Login_ID__c.field-meta.xml
<CustomField>
    <fullName>Login_ID__c</fullName>
    <label>Login ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>TA{00}</displayFormat>
        <label>Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Batch__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12:00 AM</fullName>
            </value>
            <value>
                <fullName>12:30 AM</fullName>
            </value>
            <value>
                <fullName>1:00 AM</fullName>
            </value>
            <value>
                <fullName>1:30 AM</fullName>
            </value>
            <value>
                <fullName>2:00 AM</fullName>
            </value>
            <value>
                <fullName>2:30 AM</fullName>
            </value>
            <value>
                <fullName>3:00 AM</fullName>
            </value>
            <value>
                <fullName>3:30 AM</fullName>
            </value>
            <value>
                <fullName>4:00 AM</fullName>
            </value>
            <value>
                <fullName>4:30 AM</fullName>
            </value>
            <value>
                <fullName>5:00 AM</fullName>
            </value>
            <value>
                <fullName>5:30 AM</fullName>
            </value>
            <value>
                <fullName>6:00 AM</fullName>
            </value>
            <value>
                <fullName>6:30 AM</fullName>
            </value>
            <value>
                <fullName>7:00 AM</fullName>
            </value>
            <value>
                <fullName>7:30 AM</fullName>
            </value>
            <value>
                <fullName>8:00 AM</fullName>
            </value>
            <value>
                <fullName>8:30 AM</fullName>
            </value>
            <value>
                <fullName>9:00 AM</fullName>
            </value>
            <value>
                <fullName>9:30 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:30 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:30 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:30 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:30 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:30 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <label>Session Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Theory</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12:00 AM</fullName>
            </value>
            <value>
                <fullName>12:30 AM</fullName>
            </value>
            <value>
                <fullName>1:00 AM</fullName>
            </value>
            <value>
                <fullName>1:30 AM</fullName>
            </value>
            <value>
                <fullName>2:00 AM</fullName>
            </value>
            <value>
                <fullName>2:30 AM</fullName>
            </value>
            <value>
                <fullName>3:00 AM</fullName>
            </value>
            <value>
                <fullName>3:30 AM</fullName>
            </value>
            <value>
                <fullName>4:00 AM</fullName>
            </value>
            <value>
                <fullName>4:30 AM</fullName>
            </value>
            <value>
                <fullName>5:00 AM</fullName>
            </value>
            <value>
                <fullName>5:30 AM</fullName>
            </value>
            <value>
                <fullName>6:00 AM</fullName>
            </value>
            <value>
                <fullName>6:30 AM</fullName>
            </value>
            <value>
                <fullName>7:00 AM</fullName>
            </value>
            <value>
                <fullName>7:30 AM</fullName>
            </value>
            <value>
                <fullName>8:00 AM</fullName>
            </value>
            <value>
                <fullName>8:30 AM</fullName>
            </value>
            <value>
                <fullName>9:00 AM</fullName>
            </value>
            <value>
                <fullName>9:30 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:30 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:30 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:30 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:30 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:30 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/SessionEntry__c.object-meta.xml
<CustomObject>
    <label>SessionEntry</label>
    <nameField>
        <displayFormat>SE-{000}</displayFormat>
        <label>SessionEntry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Entry</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Batch__c</referenceTo>
    <relationshipLabel>Session Entry</relationshipLabel>
    <relationshipName>Session_Entry</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Session Entry</relationshipLabel>
    <relationshipName>Sessions_Entry</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/selectsesion__c.field-meta.xml
<CustomField>
    <fullName>selectsesion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selected Session</label>
    <type>Checkbox</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Sessions Entry</relationshipLabel>
    <relationshipName>Sessions_Entry</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Session_Name__c.field-meta.xml
<CustomField>
    <fullName>Session_Name__c</fullName>
    <label>Session Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <label>Session Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Devlopement</fullName>
            </value>
            <value>
                <fullName>Theory</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
                <color>#FF0000</color>
                <label>Completed</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#419249</color>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Not yet Started</fullName>
                <color>#6633FF</color>
                <label>Not yet Started</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/classes/FactHomePageHomeTabContr.cls
public class FactHomePageHomeTabContr {

    public String fid;
    public Session__c sessn {get; set;}   
    public boolean displayPopup {get; set;}
    public List<SessionEntry__C> displayTodaysTask{get;set;}
    public List<SessionEntry__C> displayUpComingTask{get;set;}
    
    public FactHomePageHomeTabContr() {
       fid = ApexPages.currentPage().getParameters().get('Id');
       Faculty__c faclt=[select Id,Name from Faculty__c where Login_ID__c=:fid Limit 1];
       
       //Upcoming task.. 
       displayUpComingTask =new List<SessionEntry__C>();
       List<SessionEntry__C> SentryUpcList=[SELECT Id, IsDeleted, Name, Batch__c, Comment__c, Session_Type__c, Session__c,
                                            Status__c, Session_Name__c, Course_Name__c, Start_Time__c, End_Time__c, selectsesion__c 
                                            from sessionEntry__c where faculty__c=:faclt.Id limit 50];
       for(SessionEntry__C ss:SentryUpcList){
           displayUpComingTask.add(new SessionEntry__C(Course_Name__c = ss.Course_Name__c,Batch__c = ss.Batch__c,Session_Name__c=ss.Session_Name__c,
                                                       Session_Type__c=ss.Session_Type__c));
       }                                                 
    }

    // Get the Login User Name    
    public Faculty__c[] getUserName(){
        Faculty__c[] fct;
        try {
            fct = [Select Id, Name, Last_Name__c, Email_ID__c, Login_ID__c, Mobile_No__c, PIN__c, Courses__c from Faculty__c where Login_ID__c=:fid];
        }catch(Exception e) { }
        return fct;
    } 
        
    // Session Complete Table
    public Session__c[] getSessComplete(){
        Session__c[] sesscom;
        List<Faculty__c> sessionList = new List<Faculty__c>();
        sessionList = [SELECT Id, login_id__c from Faculty__c where login_id__c=:fid];
        try{
            sesscom = [SELECT Id, Name, CourseId__c, Task_Completed__c, Task__c, Session_Type__c, Status__c, Session_Status__c, FacultyID__c, Comment__c, Batch__c,
                     Date__c, Start_Time__c, End_Time__c  from Session__c  where FacultyID__c=:sessionList[0].Id and Status__c='Completed'   order by Batch__c ];
        }catch(Exception e){
             System.debug(e);
        }
        return sesscom;
    } 
        
    // Session In Progress Table
    public Session__c[] getSessProgress(){
        Session__c[] sessprg;
        List<Faculty__c> sessionList = new List<Faculty__c>();
        sessionList = [SELECT Id, login_id__c from Faculty__c where login_id__c=:fid];
        
        try{
            sessprg = [SELECT Id, Name, CourseId__c, Task_Completed__c, Task__c, Session_Type__c, Status__c, Session_Status__c, FacultyID__c, Comment__c, Batch__c,
                      Date__c, Start_Time__c, End_Time__c  from Session__c  where FacultyID__c=:sessionList[0].Id and Status__c='In Progress' order by Batch__c ];
        }catch(Exception e){
            System.debug(e);
        }
        return sessprg;
    }
        
    // Session Not Complete Table
    public Session__c[] getSessNot(){
        Session__c[] sesnot;
        List<Faculty__c> sessionList = new List<Faculty__c>();
        sessionList = [SELECT Id, login_id__c from Faculty__c where login_id__c=:fid];
        try{
            sesnot = [SELECT Id, Name, CourseId__c, Task_Completed__c, Task__c, Session_Type__c, Status__c, Session_Status__c, FacultyID__c, Comment__c, Batch__c,
                     Date__c, Start_Time__c, End_Time__c  from Session__c  where FacultyID__c=:sessionList[0].Id and Status__c='Not Started'   order by Batch__c ];
        }catch(Exception e){
            System.debug(e);
        }
        return sesnot;
    } 
    
    // Go to Pop Up Page    
    public String edId {get; set;}
    
   // public Session__c sessions;   
    public void sessEditPage() {
        sessn = [SELECT Id, Name, CourseId__c, FacultyID__c, Comment__c, Session_Type__c, Status__c, Task_Completed__c, Task__c, Test_Status__c, Batch__c, 
                    Session_Status__c, Date__c, Start_Time__c, End_Time__c from Session__c  where Id=:edId ];
        
        displayPopup = true;            
    }  
      
    public void savePopUp() {
        List<Faculty__c> fact = new List<Faculty__c>();
        try {
            fact = [SELECT Id, Name, Login_ID__c  from Faculty__c where Id=:fid  ];  
            System.debug('Chk the Fact ID ........'+ fact+'fid value is ....'+ fid);

            update this.sessn;
            System.debug('CHKKKKKKKKKKKKKKKKKK ...............'+this.sessn);
        }catch(Exception e) { }    
      displayPopup = false; 
    }      
    
    public void closePopUp() {
        displayPopup = false;    
    }           
    
    //Test Methods
    static testMethod void facHomeTest(){
        faculty__c fac=new faculty__c();
        fac.Name='Raju';
        fac.Last_Name__c='Shewad';
        fac.DOB__c=System.toDay();
        fac.Email_ID__c='baruna@ceptes.com';
        fac.Mobile_No__c='2121343456';
        fac.PIN__c=232323;
        Insert fac;
        
        Program__c prg=new Program__c();
        prg.Name='DWH';
        Insert prg;
       
        Course__c crs=new Course__c();
        crs.Name='J2ME';
        crs.ProgramId__c=prg.Id;
        Insert crs;
             
        Session__c ssn = new Session__c();
        ssn.CourseId__c = crs.Id;
        ssn.Session_Name__c = 'intro';
        ssn.Session_Type__c = 'Theory';
        ssn.Duration_In_Hour__c = 3;
        insert ssn;
        
        faculty__c fa=[select Id,Name,Login_ID__c from faculty__c where Name='Raju'];
        ApexPages.currentPage().getParameters().put('Id',fa.Login_ID__c);
        FactHomePageHomeTabContr fachm=new FactHomePageHomeTabContr();
        fachm.edId=ssn.Id;
        fachm.getUserName();
        fachm.getSessComplete();
        fachm.getSessProgress();
        fachm.getSessNot();
        fachm.sessEditPage();
        fachm.savePopUp();
        fachm.closePopUp();
        Delete fac;
    }
    
    
}