Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Batchs</relationshipLabel>
    <relationshipName>Batchs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/Time_Diff__c.field-meta.xml
<CustomField>
    <fullName>Time_Diff__c</fullName>
    <label>Time Diff</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Batch__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <label>Total Hours</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Coordinator__c/Coordinator__c.object-meta.xml
<CustomObject>
    <label>Coordinator</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coordinator</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Coordinator__c/fields/Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Mobile_No__c</fullName>
    <label>Mobile No</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Coordinator__c/fields/PIN__c.field-meta.xml
<CustomField>
    <fullName>PIN__c</fullName>
    <label>PIN</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/fields/Course_Fees__c.field-meta.xml
<CustomField>
    <fullName>Course_Fees__c</fullName>
    <label>Course Fees</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/fields/ProgramId__c.field-meta.xml
<CustomField>
    <fullName>ProgramId__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Course__c/fields/Programs__c.field-meta.xml
<CustomField>
    <fullName>Programs__c</fullName>
    <label>Programs</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core Java</fullName>
            </value>
            <value>
                <fullName>JSP</fullName>
            </value>
            <value>
                <fullName>Servlets</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>Struts</fullName>
            </value>
            <value>
                <fullName>VisualForce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/Faculty__c.object-meta.xml
<CustomObject>
    <label>Faculty</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faculty</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Email_ID__c</fullName>
    <externalId>true</externalId>
    <label>Email ID</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Login_ID__c.field-meta.xml
<CustomField>
    <fullName>Login_ID__c</fullName>
    <label>Login ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Programs__c.field-meta.xml
<CustomField>
    <fullName>Programs__c</fullName>
    <label>Programs</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Courses__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>APEX</fullName>
            </value>
            <value>
                <fullName>Asp.NET</fullName>
            </value>
            <value>
                <fullName>C#.NET</fullName>
            </value>
            <value>
                <fullName>Core Java</fullName>
            </value>
            <value>
                <fullName>JSP</fullName>
            </value>
            <value>
                <fullName>Oracle- 9i</fullName>
            </value>
            <value>
                <fullName>PLSQL</fullName>
            </value>
            <value>
                <fullName>RUBY</fullName>
            </value>
            <value>
                <fullName>Servlets</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>SQL</fullName>
            </value>
            <value>
                <fullName>Struts</fullName>
            </value>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>VB.NET</fullName>
            </value>
            <value>
                <fullName>VisualForce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>TA{00}</displayFormat>
        <label>Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Batch__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Session</relationshipLabel>
    <relationshipName>TestTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Session__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <label>Session Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Theory</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/SessionEntry__c.object-meta.xml
<CustomObject>
    <label>SessionEntry</label>
    <nameField>
        <displayFormat>SE-{000}</displayFormat>
        <label>SessionEntry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Entry</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Batch__c</referenceTo>
    <relationshipLabel>Session Entry</relationshipLabel>
    <relationshipName>Session_Entry</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Session Entry</relationshipLabel>
    <relationshipName>Sessions_Entry</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Sessions Entry</relationshipLabel>
    <relationshipName>Sessions_Entry</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Session_Name__c.field-meta.xml
<CustomField>
    <fullName>Session_Name__c</fullName>
    <label>Session Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Session_Type__c.field-meta.xml
<CustomField>
    <fullName>Session_Type__c</fullName>
    <label>Session Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Devlopement</fullName>
            </value>
            <value>
                <fullName>Theory</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/SessionEntry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
                <color>#FF0000</color>
                <label>Completed</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#419249</color>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Not yet Started</fullName>
                <color>#6633FF</color>
                <label>Not yet Started</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/classes/TestPage_CLS.cls
public class TestPage_CLS {

    public String selectProgram {get; set;}
    public List<SelectOption> corsList {get; set;}   
    public String coid;
    public String cName;
    public Boolean showText{get;set;}
    public List<TaskDetails> taskDetFromSEntry{get;set;}
    public String seletedCors{get;set;}
    public List<Batch__c> batchName{get;set;}
    
    public TestPage_CLS(){
               
    System.debug('TestSEntryList.........taskDetFromSEntry......');
        coid=ApexPages.currentPage().getParameters().get('Id');
        corsList =new List<SelectOption>();
        showText=true;
        System.debug('.............coid..........'+coid);
    }
    // Coordinator User Name
    public Coordinator__c getCorUserName(){
        Coordinator__c cor;
//        cor = [Select Id, Name, Last_Name__c, Email_ID__c,Login_ID__c,Mobile_No__c,PIN__c from Coordinator__c where Login_ID__c=:coid];
        cor = [Select Id, Name, Last_Name__c, Email_ID__c,Login_ID__c,Mobile_No__c,PIN__c from Coordinator__c ];

        return cor;
    }
    
    // Select Program List
    public List<SelectOption> getProgName(){
        List<Program__c> prgm = [SELECT Id, Name from Program__c  order by Name ];
        List<SelectOption> popt = new List<SelectOption>();
            popt.add(new SelectOption('', '--Select--'));
                for(Program__c ps:prgm) {
                 popt.add(new SelectOption(ps.Id, ps.Name));
                 }        
          return popt;
        }
        
    // Onchange Program        
    public void onChangeProgram() {
        showText=false;
        System.debug('Progam I............D is'+selectProgram);
        corsList =new List<SelectOption>();
        List<Course__c> cours = [SELECT Id, Name, Programs__c,Course_Fees__c, Course_Name__c, ProgramId__c from Course__c 
                                  where  ProgramId__c=:selectProgram  order by Name ];
        for(Course__c cs:cours)
            corsList.add(new SelectOption(cs.Id, cs.Name));
    }
    
   public void showBatchStatus(){
       showText=false;
       taskDetFromSEntry = new  List<TaskDetails>();
       batchName = new List<Batch__c>();
       try{
           List<Batch__c> batList=[Select Id,Name,Start_Date__c,Total_Hours__c,Time_Diff__c  from Batch__c where CourseId__c=:seletedCors ];
           Course__c crsName=[Select Id,Name from Course__c where Id=:seletedCors];
           cName=crsName.Name;
           List<SessionEntry__c> sEntryList=[SELECT Id,  Name, Faculty__c, Batch__c, Comment__c, Session_Type__c, Session__c, Status__c, Session_Name__c, Course_Name__c, Start_Time__c, End_Time__c, 
                                   selectsesion__c from SessionEntry__c where Course_Name__c=:cName ]; 
          
           Map<String,List<SessionEntry__c>> batchSessionMap =new  Map<String,List<SessionEntry__c>>();
                for(SessionEntry__c ssent:sEntryList){
                    List<SessionEntry__c> sestemp = batchSessionMap.get(ssent.batch__c);
                    if(sestemp == null){
                        sestemp = new List<SessionEntry__c>();
                        sestemp.add(ssent);
                        batchSessionMap.put(ssent.batch__c,sestemp);
                    }else
                        sestemp.add(ssent);
                    
                }
                
            for(Batch__c b:batList){
                batchName.add(new Batch__c(Name = b.Name));
                for(String key : batchSessionMap.keyset()){
                    List<SessionEntry__c> sList = batchSessionMap.get(key);
                    if(b.Id == key){
                        TaskDetails tsk = new TaskDetails();        
                        tsk.sentList=new List<SesEntRec>();
                        tsk.batchName=b.Name;
                        tsk.batchSDate=String.valueOf(b.Start_Date__c);
                        tsk.timeDuration=b.Time_Diff__c;
                        for(SessionEntry__c sce : sList){
                            if(sce.Faculty__c == null)
                                tsk.sentList.add(new SesEntRec(false,sce));
                            else
                                tsk.sentList.add(new SesEntRec(true,sce));
                        }
                        taskDetFromSEntry.add(tsk);
                        System.debug('.........taskDetFromSEntry...........'+taskDetFromSEntry);
                    }
                } 
            }
          
       }catch(Exception e){System.debug('.......Exception block....'+e);}  
   }        
    
     public PageReference saveSessEntry(){
         showText=false;
         System.debug('.........cname is....'+cName);
        try{
            List<SessionEntry__c> sEntryList=[SELECT Id,  Name, Faculty__c, Batch__c, Comment__c, Session_Type__c, Session__c, Status__c, Session_Name__c, Course_Name__c, Start_Time__c, End_Time__c, 
                                    selectsesion__c from SessionEntry__c where Course_Name__c=:cName AND Faculty__c = ''];
            for(TaskDetails tsk:taskDetFromSEntry)
                for(SesEntRec tsent:tsk.sentList)
                     for(SessionEntry__c sent:sEntryList)
                        if(tsent.checked && tsent.sec.Faculty__c != null  && tsent.sec.Id == sent.Id){
                            sent.faculty__c = tsent.sec.Faculty__c;
                            sent.Status__c='In Progress';
                            update sent;
                            System.debug('.....updated Records.............'+sent);
                        }
            showBatchStatus();            
        }catch(Exception e){System.debug('..Exception is........'+e);} 
        return null;
    }
    
    
    // Get Completed Batch  
    public List<Batch__c> getBatchComplete(){
        List<Batch__c> batList;
        try {
             batList = [SELECT Id, Name, CourseId__c, BatchId__c, Faculty_Id__c, Status__c,  End_Date__c, Start_Date__c from Batch__c
                        where Status__c = 'Completed' AND  CourseId__c=:seletedCors  order by Name ];
        
        }catch(Exception e){} 
        return batList;
    }  
    
    // Get In Progress Batch
    public List<Batch__c> getBatchProgress(){
        List<Batch__c> batIp;
        try {
            batIp = [SELECT Id, Name, CourseId__c, BatchId__c, Faculty_Id__c, Status__c,  End_Date__c, Start_Date__c from Batch__c
                     where Status__c = 'In Progress' and  CourseId__c=:seletedCors  order by Name ];
       
        }catch(Exception e){}
        return batIp;
    }
       
    // Get Not Started Batch
    public  List<Batch__c> getBatchNotStart(){
        List<Batch__c> batn; 
        try {        
            batn = [SELECT Id, Name, CourseId__c, BatchId__c, Faculty_Id__c, Status__c,  End_Date__c, Start_Date__c from Batch__c
                    where Status__c = 'Not Started' and  CourseId__c=:seletedCors  order by Name ];
        }catch(Exception e){}
        return batn;
    }
  
    
    public class TaskDetails{
        public String batchName{get;set;}
        public String batchSDate{get;set;}
        public Decimal timeDuration{get;set;}
        public List<SesEntRec> sentList{get;set;}
        public TaskDetails(){}

         public  List<SelectOption> getFacNameList(){
            List<SelectOption> options=new List<SelectOption>();
            List<Faculty__C> fList=[Select Id,Name from Faculty__c Limit 100];
            options.add(new SelectOption('','-select-'));
            for(Faculty__c fa:fList)
                options.add(new SelectOption(fa.Id,fa.Name)); 
                return options;
            } 
     }
     public class SesEntRec{ 
        public Boolean checked{get;set;}
        public Boolean disable{get;set;} 
        public SessionEntry__c sec {get;set;}
        public SesEntRec(Boolean b,SessionEntry__c sc){    
        checked=b;
        disable=b;
        sec=sc;               
        } 
    }
    
    
}