Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Cost_Incurred_In_Promotions__c.field-meta.xml
<CustomField>
    <fullName>Cost_Incurred_In_Promotions__c</fullName>
    <label>Cost Incurred In Promotions</label>
    <summarizedField>UB_Promotion__c.UB_PromotionalCost__c</summarizedField>
    <summaryForeignKey>UB_Promotion__c.UB_Outlet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Current_Number_Of_Events__c.field-meta.xml
<CustomField>
    <fullName>Current_Number_Of_Events__c</fullName>
    <label>Total Number Of Events</label>
    <summaryForeignKey>UB_Event__c.Outlet__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Current_Order_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Order_Amount__c</fullName>
    <label>Total Order Amount</label>
    <summarizedField>UB_Order__c.UB_Total_Price__c</summarizedField>
    <summaryForeignKey>UB_Order__c.UB_Outlet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Total_Expenditure_In_Events__c.field-meta.xml
<CustomField>
    <fullName>Total_Expenditure_In_Events__c</fullName>
    <label>Total Expenditure In Events</label>
    <summarizedField>UB_Event__c.UB_ActualEventCost__c</summarizedField>
    <summaryForeignKey>UB_Event__c.Outlet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Total_Number_Of_Orders__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_Of_Orders__c</fullName>
    <label>Total Number Of Orders</label>
    <summaryForeignKey>UB_Order__c.UB_Outlet__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Total_Number_Of_Promotions__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_Of_Promotions__c</fullName>
    <label>Total Number Of Promotions</label>
    <summaryForeignKey>UB_Promotion__c.UB_Outlet__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/UB_KAM__c.field-meta.xml
<CustomField>
    <fullName>UB_KAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Key Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Volume_Sales_Target_for_Year__c.field-meta.xml
<CustomField>
    <fullName>Volume_Sales_Target_for_Year__c</fullName>
    <label>Volume Sales Target for Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Yearly_Activity_Target__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Activity_Target__c</fullName>
    <label>Yearly Activity Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Yearly_Revenue_Target__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Revenue_Target__c</fullName>
    <label>Yearly Revenue Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Yearly_Target_for_Branding_Activity__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Target_for_Branding_Activity__c</fullName>
    <label>Yearly Target for Events</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Yearly_Target_for_Branding_Activity_Valu__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Target_for_Branding_Activity_Valu__c</fullName>
    <label>Yearly Target Event Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Yearly_Target_for_Promotional_Event__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Target_for_Promotional_Event__c</fullName>
    <label>Yearly Target for Promos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Yearly_Target_Promotional_Event_Value__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Target_Promotional_Event_Value__c</fullName>
    <label>Yearly Target Promo Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Order__c/UB_Order__c.object-meta.xml
<CustomObject>
    <label>UB Order</label>
    <nameField>
        <label>UB Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UB Order</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Order__c/fields/UB_Outlet__c.field-meta.xml
<CustomField>
    <fullName>UB_Outlet__c</fullName>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>UB Order</relationshipLabel>
    <relationshipName>UB_Order</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Order__c/fields/Volume_Sale__c.field-meta.xml
<CustomField>
    <fullName>Volume_Sale__c</fullName>
    <formula>UB_Quantity__c * 0.750</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Volume Sale</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/classes/UB_Sales_CLS.cls
public class UB_Sales_CLS {

//public string usr;
public decimal BudgetTarget {get; set;}
public decimal BudgetAchieved {get; set;}
public integer HistoryCount{get; set;}
public Integer UBOrderVolumeSales {get; set;}
public Account Outlet {get;set;}
public Boolean showKAM {get; set;}
public String KeyAccMetric_name {get;set;}
public List<AggregateResult> lstUbSalesOrder {get; set;}
public string totalUBSales {get; set;}

   /* public user getusername() {
      user usr= [SELECT id, Name FROM User WHERE id =: UserInfo.getUserid()];
        return usr;
    }*/
     
    public List<SelectOption> getItems() {
        List<Account> lstacc = [SELECT Name FROM Account WHERE UB_KAM__c =: UserInfo.getUserid()];
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '-Select-'));
        for(integer i=0; i<lstacc.size(); i++) {
            options.add(new SelectOption(lstacc[i].Id,lstacc[i].Name));
        }
        return options;
    }
        
    public List<Account> getOutletDetails() {
               
        showKAM = true;             
        List<Account> Outletdet = new List<Account>();
        Outletdet = [SELECT  Yearly_Revenue_Target__c, Current_Order_Amount__c, Volume_Sales_Target_for_Year__c, Total_Number_Of_Orders__c, Current_Number_Of_Events__c, Yearly_Target_for_Branding_Activity__c, Yearly_Target_for_Promotional_Event__c, Total_Number_Of_Promotions__c, Yearly_Target_for_Branding_Activity_Valu__c, Total_Expenditure_In_Events__c, Cost_Incurred_In_Promotions__c, Yearly_Target_Promotional_Event_Value__c,  Yearly_Activity_Target__c FROM Account WHERE ID =: KeyAccMetric_name]; 
        
        for(Integer j=0; j<Outletdet.size(); j++) {         
            BudgetTarget = Outletdet[j].Yearly_Target_for_Branding_Activity_Valu__c + Outletdet[j].Yearly_Target_Promotional_Event_Value__c;
        }       
        
        for(Integer k=0; k<Outletdet.size(); k++) { 
            BudgetAchieved = Outletdet[k].Total_Expenditure_In_Events__c + Outletdet[k].Cost_Incurred_In_Promotions__c;  
        }      

        List<AccountHistory> Acchstr = new List<AccountHistory>();
            Acchstr = [SELECT Account.Name, Account.UB_KAM__c FROM AccountHistory WHERE account.id =: KeyAccMetric_name AND Account.UB_KAM__c =:UserInfo.getUserid()];
            
            HistoryCount = Acchstr.size();
            
        lstUbSalesOrder = [SELECT SUM(Volume_Sale__c)sv FROM UB_Order__c where UB_Outlet__c =:KeyAccMetric_name ];            
            System.debug('SUM Value=========================>>>>>>.'+lstUbSalesOrder);
        if(lstUbSalesOrder.size()>0){
            totalUBSales = string.Valueof(lstUbSalesOrder[0].get('sv'));
        }
         
        return Outletdet;                 
    }
        
}