Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Cost_Incurred_In_Promotions__c.field-meta.xml
<CustomField>
    <fullName>Cost_Incurred_In_Promotions__c</fullName>
    <label>Cost Incurred In Promotions</label>
    <summarizedField>UB_Promotion__c.UB_PromotionalCost__c</summarizedField>
    <summaryForeignKey>UB_Promotion__c.UB_Outlet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Current_Number_Of_Events__c.field-meta.xml
<CustomField>
    <fullName>Current_Number_Of_Events__c</fullName>
    <label>Total Number Of Events</label>
    <summaryForeignKey>UB_Event__c.Outlet__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Current_Order_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Order_Amount__c</fullName>
    <label>Total Order Amount</label>
    <summarizedField>UB_Order__c.UB_Total_Price__c</summarizedField>
    <summaryForeignKey>UB_Order__c.UB_Outlet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Days_Since_Activity__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Activity__c</fullName>
    <formula>TODAY() - LastActivityDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Activity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Total_Expenditure_In_Events__c.field-meta.xml
<CustomField>
    <fullName>Total_Expenditure_In_Events__c</fullName>
    <label>Total Expenditure In Events</label>
    <summarizedField>UB_Event__c.UB_ActualEventCost__c</summarizedField>
    <summaryForeignKey>UB_Event__c.Outlet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Total_Number_Of_Orders__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_Of_Orders__c</fullName>
    <label>Total Number Of Orders</label>
    <summaryForeignKey>UB_Order__c.UB_Outlet__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Total_Number_Of_Promotions__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_Of_Promotions__c</fullName>
    <label>Total Number Of Promotions</label>
    <summaryForeignKey>UB_Promotion__c.UB_Outlet__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/UB_KAM__c.field-meta.xml
<CustomField>
    <fullName>UB_KAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Key Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Volume_Sales_Target_for_Year__c.field-meta.xml
<CustomField>
    <fullName>Volume_Sales_Target_for_Year__c</fullName>
    <label>Volume Sales Target for Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Yearly_Activity_Target__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Activity_Target__c</fullName>
    <label>Yearly Activity Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Yearly_Revenue_Target__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Revenue_Target__c</fullName>
    <label>Yearly Revenue Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Yearly_Target_for_Branding_Activity__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Target_for_Branding_Activity__c</fullName>
    <label>Yearly Target for Events</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Yearly_Target_for_Branding_Activity_Valu__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Target_for_Branding_Activity_Valu__c</fullName>
    <label>Yearly Target Event Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Yearly_Target_for_Promotional_Event__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Target_for_Promotional_Event__c</fullName>
    <label>Yearly Target for Promos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/Yearly_Target_Promotional_Event_Value__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Target_Promotional_Event_Value__c</fullName>
    <label>Yearly Target Promo Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/classes/UB_Outlet_CTRL.cls
public class UB_Outlet_CTRL {

public String SelectOutlet {get; set;}

    public User getOwnerName() {
        User usr = [Select Id, Name from User where Id=:UserInfo.getUserId() ];
        return usr;   
    }
     
    public List<SelectOption> getOutletName() {
        List<SelectOption> lstOutlet = new List<SelectOption>();
        List<Account> lstAccount = [ Select Id, Name, UB_KAM__c from Account where UB_KAM__c=:UserInfo.getUserId() order by Name ];
        
        for(Account acc:lstAccount ) {
            lstOutlet.add(new SelectOption(acc.Id, acc.Name));
        }             
        return lstOutlet;
    }
    
    public List<Account> getOutletTable() {
        List<Account> lstAcc = [ Select Id, Name, UB_KAM__c, Total_Number_Of_Orders__c, Current_Order_Amount__c, Total_Expenditure_In_Events__c, Current_Number_Of_Events__c, 
                Total_Number_Of_Promotions__c, Cost_Incurred_In_Promotions__c, Yearly_Target_for_Branding_Activity__c, Yearly_Target_for_Branding_Activity_Valu__c, 
                Yearly_Target_for_Promotional_Event__c, Yearly_Target_Promotional_Event_Value__c, Yearly_Revenue_Target__c,  Volume_Sales_Target_for_Year__c, 
                Yearly_Activity_Target__c, Days_Since_Activity__c from Account  ];
    
        
                
        return null;
    }              
}