Reetan.Nayak Dev 25/force-app/main/default/objects/Account/fields/UB_Location__c.field-meta.xml
<CustomField>
    <fullName>UB_Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Product2/fields/UB_Brand__c.field-meta.xml
<CustomField>
    <fullName>UB_Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Power</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Luxury</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Campaign_Member__c/UB_Campaign_Member__c.object-meta.xml
<CustomObject>
    <label>UB Campaign Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UB Campaign Member</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Campaign_Member__c/fields/UB_Outlet__c.field-meta.xml
<CustomField>
    <fullName>UB_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Campaign_Member</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Coupon__c/UB_Coupon__c.object-meta.xml
<CustomObject>
    <label>UB Coupon</label>
    <nameField>
        <label>UBCoupon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UB Coupon</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Coupon__c/fields/QR_Image__c.field-meta.xml
<CustomField>
    <fullName>QR_Image__c</fullName>
    <formula>IMAGE( QR_Image_URL__c , &quot;test&quot; ,75, 75)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QR Image</label>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Coupon__c/fields/QR_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>QR_Image_URL__c</fullName>
    <formula>&quot;https://chart.googleapis.com/chart?chs=150x150&amp;cht=qr&amp;chl=&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QR Image URL</label>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Coupon__c/fields/QR_URL__c.field-meta.xml
<CustomField>
    <fullName>QR_URL__c</fullName>
    <formula>&quot;http://sdo-134eb721b22.force.com/qr&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QR URL</label>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Coupon__c/fields/UB_Brand__c.field-meta.xml
<CustomField>
    <fullName>UB_Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Power</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Luxury</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Coupon__c/fields/UB_CampaignMember__c.field-meta.xml
<CustomField>
    <fullName>UB_CampaignMember__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Member</label>
    <referenceTo>UB_Campaign_Member__c</referenceTo>
    <relationshipLabel>UB Coupon</relationshipLabel>
    <relationshipName>UB_Coupon</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Coupon__c/fields/UB_Coupon_Number__c.field-meta.xml
<CustomField>
    <fullName>UB_Coupon_Number__c</fullName>
    <displayFormat>CUPNCampOutlet-{0000}</displayFormat>
    <label>Coupon Number</label>
    <type>AutoNumber</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Coupon__c/fields/UB_Location__c.field-meta.xml
<CustomField>
    <fullName>UB_Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Coupon__c/fields/UB_Outlet__c.field-meta.xml
<CustomField>
    <fullName>UB_Outlet__c</fullName>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>UB Coupon</relationshipLabel>
    <relationshipName>UB_Coupon</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Coupon__c/fields/UB_Product__c.field-meta.xml
<CustomField>
    <fullName>UB_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>UB Coupon</relationshipLabel>
    <relationshipName>UB_Coupon</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Coupon__c/fields/UB_Valid_From__c.field-meta.xml
<CustomField>
    <fullName>UB_Valid_From__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/UB_Coupon__c/fields/UB_Valid_To__c.field-meta.xml
<CustomField>
    <fullName>UB_Valid_To__c</fullName>
    <formula>UB_Valid_From__c + 30</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/classes/Coupon_View_CLS.cls
Public Class Coupon_View_CLS {

Public string strCouPonID;
Public UB_Coupon__c Coupon {get; set;}

    Public Coupon_View_CLS() {

    strCouPonID = ApexPages.currentPage().getParameters().get('id');
    system.debug('<<<<<<<<<< ' + strCouPonID );
     /* list<UB_Coupon__c> lstCoupon = [select id,UB_Brand__c,UB_Contact__r.Name,UB_Coupon_Number__c,UB_Location__c,UB_Outlet__r.name from UB_Coupon__c where id =:strCouPonID ];

    if(lstCoupon > 0)
    strName=lstCoupon[0].UB_Brand__c;
    */

    /*strUbslCouPonNumber=
    strBrandName=
    strProduct=
    strCouPonID=
    */
    // Coupon = [select id,UB_Brand__c,UB_Contact__r.Name,UB_Coupon_Number__c,UB_Location__c,UB_Outlet__r.name from UB_Coupon__c where id =:strCouPonID ];

        if (strCouPonID != null) {
           Coupon = [select id, QR_image__c,QR_Image_Url__c, QR_URL__c, UB_Brand__c, UB_CampaignMember__r.Name, UB_Coupon_Number__c, UB_Location__c, UB_Product__r.Name, UB_Outlet__r.name, UB_Valid_From__c, UB_Valid_To__c from UB_Coupon__c where id =:strCouPonID ]; 
        }
    }

}