Reetan.Nayak Dev 25/force-app/main/default/objects/Favorites__c/Favorites__c.object-meta.xml
<CustomObject>
    <description>Contains records for all favorites including:  Account, Contact, and Opportunities</description>
    <label>Favorites</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Favorites__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference the Account record that has been marked as a Favorite.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Favorites</relationshipLabel>
    <relationshipName>Favorites1</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Favorites__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference the Contact record that has been marked as a Favorite.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Favorites</relationshipLabel>
    <relationshipName>Favorites1</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Favorites__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference the Lead record that has been marked as a Favorite.</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Favorites</relationshipLabel>
    <relationshipName>Favorites1</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Favorites__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference the Opportunity record that has been marked as a Favorite.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Favorites</relationshipLabel>
    <relationshipName>Favorites1</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Favorites__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Determine what type of object does the favorite reference to.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Favorites__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference the User who marked the record as a Favorite.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Favorites1</relationshipName>
    <type>Lookup</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/System_Event_Log__c/System_Event_Log__c.object-meta.xml
<CustomObject>
    <description>Custom object that holds all of the error,system,event logs generated on every code execution.</description>
    <label>System Event Log</label>
    <nameField>
        <displayFormat>SL-{00000}</displayFormat>
        <label>System Event Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Event Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/classes/MarkFavorites.cls
/**
* @author Original: Robby Angeles (502068421) Cloud Sherpas/GEHC Last Modified: Robby Angeles (502068424) Cloud Sherpas/GEHC
* @date Original: 14 Mar 2012, Last Modified 02 Oct 2012
* @description Class that facilitates marking of Account, Contact and Opportunity records as Favorite via Favorites custom object.
*/
global class MarkFavorites {
  
  /**
  * @author Original: Robby Angeles (502068421) Cloud Sherpas/GEHC Last Modified: Robby Angeles (502068424) Cloud Sherpas/GEHC
  * @date Original: 14 Mar 2012, Last Modified 20 Jun 2012
  * @description Method that dynamically queries the Favorites custom object to check if a record is already marked by the user as favorite and if not creates a new favorites record based of the record id, object type and logged in user id.
  * @param recId ID of record to be added as a Favorite.
    * @param objType sObject type of the record being added as a Favorite.
    * @return String Success or error message of the nethod.
  */

  webservice static String markRecordAsFavorite(String recId, String objType){
    String retVal = '';
    
    System_Event_Log__c sLog;
    SystemEventLogDML sLogDML = new SystemEventLogDML();
    
    try{
      String qStr = 'Select Id From Favorites__c Where ';
      
      List<Favorites__c> favList = new List<Favorites__c>();
      
      if(objType == 'Account'){
        qStr = qStr + ' Account__c = \'' + recId + '\' And Type__c = \'Account\'';
      }
      else if(objType == 'Contact'){
        qStr = qStr + ' Contact__c = \'' + recId + '\' And Type__c = \'Contact\'';
      }
      else if(objType == 'Opportunity'){
        qStr = qStr + ' Opportunity__c = \'' + recId + '\' And Type__c = \'Opportunity\'';
      }
      else if(objType == 'Lead'){
        qStr = qStr + ' Lead__c = \'' + recId + '\' And Type__c = \'Lead\'';
      }   
      qStr += ' And User__c = \'' + UserInfo.getUserId() + '\'';
      favList = database.query(qStr);
      if(favList.size() == 1){
        return 'exists';
      }
      else if(favList.size() == 0){
        
        Favorites__c fav = new Favorites__c();  
        fav.User__c = UserInfo.getUserId();
        if(objType == 'Account'){
          fav.Account__c = recId;
          fav.Type__c     = 'Account';
        }
        else if(objType == 'Contact'){
          fav.Contact__c = recId;
          fav.Type__c     = 'Contact';
        }
        else if(objType == 'Opportunity'){
          fav.Opportunity__c = recId;
          fav.Type__c     = 'Opportunity';
        }
        else if(objType == 'Lead'){
          fav.Lead__c = recId;
          fav.Type__c     = 'Lead';
        }       
        insert fav;
        return 'success';
      }
    }
    catch(Exception e){
      //log the exception on the system event log object
            sLog = sLogDML.generateSysLog('MarkFavorites.markRecordAsFavorite', e.getMessage(), '', slogDml.EvtType[0], UserInfo.getUserId());
            insert sLog;
            
      return 'An error was encountered while updating this record: ' + e.getMessage();
    }
    return 'An error was encountered while updating this record.';
  }
  
}