Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/Faculty__c.object-meta.xml
<CustomObject>
    <label>Faculty</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faculty</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Course_Details__c.field-meta.xml
<CustomField>
    <fullName>Course_Details__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Course Details</label>
    <type>Checkbox</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Course_Offered__c.field-meta.xml
<CustomField>
    <fullName>Course_Offered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Course Offered</label>
    <type>Checkbox</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Courses__c.field-meta.xml
<CustomField>
    <fullName>Courses__c</fullName>
    <label>Courses</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Force</fullName>
            </value>
            <value>
                <fullName>JAVA</fullName>
            </value>
            <value>
                <fullName>.NET</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Courses_Association__c.field-meta.xml
<CustomField>
    <fullName>Courses_Association__c</fullName>
    <label>Courses Association</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Advanced Developer</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Advanced Administrator</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Email_ID__c</fullName>
    <externalId>true</externalId>
    <label>Email ID</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Language_Known__c.field-meta.xml
<CustomField>
    <fullName>Language_Known__c</fullName>
    <label>Language Known</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bengali</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>Malayalam</fullName>
            </value>
            <value>
                <fullName>Tamil</fullName>
            </value>
            <value>
                <fullName>Telugu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Login_ID__c.field-meta.xml
<CustomField>
    <fullName>Login_ID__c</fullName>
    <label>Login ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Divorsed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Programs__c.field-meta.xml
<CustomField>
    <fullName>Programs__c</fullName>
    <label>Programs</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Courses__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>APEX</fullName>
            </value>
            <value>
                <fullName>Asp.NET</fullName>
            </value>
            <value>
                <fullName>C#.NET</fullName>
            </value>
            <value>
                <fullName>Core Java</fullName>
            </value>
            <value>
                <fullName>JSP</fullName>
            </value>
            <value>
                <fullName>Oracle- 9i</fullName>
            </value>
            <value>
                <fullName>PLSQL</fullName>
            </value>
            <value>
                <fullName>RUBY</fullName>
            </value>
            <value>
                <fullName>Servlets</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>SQL</fullName>
            </value>
            <value>
                <fullName>Struts</fullName>
            </value>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>VB.NET</fullName>
            </value>
            <value>
                <fullName>VisualForce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>.NET</fullName>
            </value>
            <value>
                <fullName>APEX</fullName>
            </value>
            <value>
                <fullName>JAVA</fullName>
            </value>
            <value>
                <fullName>ORACLE</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>SQL</fullName>
            </value>
            <value>
                <fullName>VisualForce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Technical_Experience__c.field-meta.xml
<CustomField>
    <fullName>Technical_Experience__c</fullName>
    <label>Technical Experience</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Technology_Experts__c.field-meta.xml
<CustomField>
    <fullName>Technology_Experts__c</fullName>
    <label>Technology Experts</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JAVA</fullName>
            </value>
            <value>
                <fullName>APEX</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>ORACLE</fullName>
            </value>
            <value>
                <fullName>Visual Force</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Test_Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Test_Questionnaire__c</fullName>
    <label>Test Questionnaire</label>
    <type>TextArea</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Time_Slots__c.field-meta.xml
<CustomField>
    <fullName>Time_Slots__c</fullName>
    <label>Time Slots from</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>08:00</fullName>
            </value>
            <value>
                <fullName>09:00</fullName>
            </value>
            <value>
                <fullName>10:00</fullName>
            </value>
            <value>
                <fullName>11:00</fullName>
            </value>
            <value>
                <fullName>12:00</fullName>
            </value>
            <value>
                <fullName>13:00</fullName>
            </value>
            <value>
                <fullName>14:00</fullName>
            </value>
            <value>
                <fullName>15:00</fullName>
            </value>
            <value>
                <fullName>16:00</fullName>
            </value>
            <value>
                <fullName>17:00</fullName>
            </value>
            <value>
                <fullName>18:00</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Training_Experience__c.field-meta.xml
<CustomField>
    <fullName>Training_Experience__c</fullName>
    <label>Training Experience</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Work_Experience__c.field-meta.xml
<CustomField>
    <fullName>Work_Experience__c</fullName>
    <label>Work Experience</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/Faculty__c/fields/Years_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_of_Experience__c</fullName>
    <label>Years of Experience</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/classes/CordFacultyRegdController.cls
public class CordFacultyRegdController {

    public List<Faculty__c> selectFaculty { get; set;}
    public Faculty__c faculty {get; set;}
    public Boolean showFaculty {get; set;}    
    public Integer selectPage {get; set;}
    public String facId{get;set;}
    private final Faculty__c factl;  
    
    
    public CordFacultyRegdController() {
        this.faculty = new Faculty__c();
        this.selectFaculty = (List<Faculty__c>) facultyRecords.getRecords();        
        }
        
    public CordFacultyRegdController(ApexPages.StandardSetController controller) {
       this.factl = (Faculty__c)controller.getRecord(); 
    }
    
    
    public ApexPages.StandardSetController facultyRecords {
        get {
            if(facultyRecords == null) {
                facultyRecords = new ApexPages.StandardSetController(Database.getQueryLocator( [SELECT Id,  Name, Last_Name__c, Email_ID__c, Mobile_No__c from Faculty__c  order by Name ]));
                facultyRecords.setPageSize(6);
                facultyRecords.setpageNumber(0);
                }
            return facultyRecords;
        }
        set;
    }    
     
/*     public List<Faculty__c> getSelectFaculty() {
         return (List<Faculty__c>) facultyRecords.getRecords();
    }    */
    
           
    
    // Saving the Faculty Record    
    public void facultySavePage() {
      try {
        insert this.faculty;
        facultyRecords = null;
        this.selectFaculty = (List<Faculty__c>) facultyRecords.getRecords();  
        
        //  Sending Email         
        List<Faculty__c> faclist = new List<Faculty__c>();
        faclist = [SELECT Id, Name, DOB__c, Email_ID__c, Login_ID__c, Gender__c, Last_Name__c, Mobile_No__c, PIN__c from Faculty__c
               //    where Name=:ApexPages.currentPage().getParameters().get('pg:fm:pgblk:pbs:pbsi:facn') ];                     
                   where Name=:ApexPages.currentPage().getParameters().get('pg:cordFactTab:compg:fm:pgblk:pbs:pbsi:facn') ];
        Messaging.SingleEmailMessage email=new Messaging.SingleEmailMessage();
        email.setSubject( 'Account Setup Notification');    
        email.setToAddresses( new String[]{faclist[0].Email_ID__c} );
        email.setPlainTextBody( 'Hello  '+faclist[0].Name+'\n\n'+ 'Thank you for Registering with us.\n\nYour UNIQUE User Name is :\n\nUser Name: '+faclist[0].Login_ID__c+
                          '\nDefault Password is: ceptes321' +
                          '\n\nNow get started by signing up online to view all your course details and get updates on your course status.'+
                          '\nFor queries related to account logins, Please Send Email to:'+
                          '\ntraining@ceptes.com\n\nHappy Learning \n\nSincerely,\nCTP Program Team ');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});    
        } catch(Exception e) { }
        showFaculty = false;
    }
    
    
    // Cancel to Faculty Detail Page.
    public PageReference facultyCancelPage() {
        PageReference ref = new PageReference('/apex/FacultyRegdPage');
        ref.setRedirect(true);
        return ref;
    }       
    
    public PageReference doNewFaculty() {
        this.showFaculty = true;
        return null;
    }    
    
/////////////////////    
    public void nextButton() {
        facultyRecords.next();
        this.selectFaculty = (List<Faculty__c>) facultyRecords.getRecords();        
        }

    public void previousButton() {
        facultyRecords.previous();
        this.selectFaculty = (List<Faculty__c>) facultyRecords.getRecords(); 
        }    

    public void firstButton() {
        facultyRecords.first();
        this.selectFaculty = (List<Faculty__c>) facultyRecords.getRecords(); 
        }    

    public void lastButton() {
        facultyRecords.last();
        this.selectFaculty = (List<Faculty__c>) facultyRecords.getRecords(); 
        }    

    public Integer getPageNo(){
        return facultyRecords.getPageNumber();
    }   

    public List<Integer> getPageNos(){
        List<Integer> lst = new List<Integer>();
          for(Integer i=1; i<=getTotalPageNumber(); i++) {
            lst.add(i);
        }
         return lst;
    }   
    
    public Integer getTotalPageNumber(){
        Integer n = TotalRecords - (pageSize * (TotalRecords / pageSize));
        if(n == 0){
            return TotalRecords / pageSize;
        }else
         return (TotalRecords / pageSize) + 1;
    }
    
    public Integer pageSize {
       get {
            return facultyRecords.getPageSize();
        }
        set;
    }       
    
    public Integer TotalRecords {
        get {
            return facultyRecords.getResultSize();
        }
        set;
    }
 
    public Boolean getDisableNext(){
        return facultyRecords.getHasNext();
    }
    
    public Boolean getDisablePrevious(){
        return facultyRecords.getHasPrevious();
    }
    
    public void onClickPageNo() {
    System.debug('selectPage.......' + selectPage);
        facultyRecords.setpageNumber(selectPage);
        this.selectFaculty = (List<Faculty__c>) facultyRecords.getRecords(); 
     }    
     
   public void deleteRecords(){
          
     try{
         Faculty__c fac=[SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, Address__c, City__c, Course_Details__c, Course_Offered__c, 
                         Courses_Association__c, Courses__c, DOB__c, Date_of_Joining__c, Email_ID__c, Expertise__c, Gender__c, Language_Known__c, Last_Name__c, Login_ID__c, Marital_Status__c, Mobile_No__c, PIN__c, Programs__c,
                         Skills__c, State__c, Technical_Experience__c, Technology_Experts__c, Test_Questionnaire__c, Time_Slots__c, Training_Experience__c, Work_Experience__c, Years_of_Experience__c from faculty__c where Id=:facId LIMIT 1];
         System.debug('faculty Id is+++++++++++++++++++'+facId);                
         delete fac;
         facultyRecords = null;
         this.selectFaculty = (List<Faculty__c>) facultyRecords.getRecords();        
     } catch(Exception e) {}
       showFaculty = false;
    
    }  
    
    //Test Methods
    static testMethod void testFaculty() {
        faculty__c fac=new faculty__c();
        fac.Name='Rakesh';
        fac.Last_Name__c='Prahaja';
        fac.Email_ID__c='baruna@ceptes.com';
        fac.DOB__c=System.toDay();
        fac.Mobile_No__c='1234567890';
        fac.PIN__c=332244;
        insert fac;
            
        CordFacultyRegdController CordFactRegd = new CordFacultyRegdController();
        CordFactRegd.facultySavePage();
        CordFactRegd.facultyCancelPage();
        CordFactRegd.doNewFaculty();
        CordFactRegd.nextButton();
        CordFactRegd.previousButton();
        CordFactRegd.firstButton();
        CordFactRegd.lastButton();
        CordFactRegd.getPageNo();
        CordFactRegd.getPageNos();
        CordFactRegd.getTotalPageNumber();
        CordFactRegd.getDisableNext();
        CordFactRegd.getDisablePrevious();
        CordFactRegd.selectPage = 6;
        CordFactRegd.onClickPageNo();
        CordFactRegd.deleteRecords();           
    }
 
}