Reetan.Nayak Dev 25/force-app/main/default/objects/System_Event_Log__c/System_Event_Log__c.object-meta.xml
<CustomObject>
    <description>Custom object that holds all of the error,system,event logs generated on every code execution.</description>
    <label>System Event Log</label>
    <nameField>
        <displayFormat>SL-{00000}</displayFormat>
        <label>System Event Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Event Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Reetan.Nayak Dev 25/force-app/main/default/objects/System_Event_Log__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>Type of System Event Log (Error,Debug,Info)</description>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/System_Event_Log__c/fields/Log_Source__c.field-meta.xml
<CustomField>
    <fullName>Log_Source__c</fullName>
    <description>Name of Apex class/method where system event was originated</description>
    <label>Log Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/System_Event_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/objects/System_Event_Log__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <description>Error code/Event code/Status code that identifies the log message</description>
    <label>Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Reetan.Nayak Dev 25/force-app/main/default/classes/SystemEventLogDML.cls
/**
* @author Jesfer Baculod (502068421) Cloud Sherpas/GEHC
* @date Original: 27 Aug 2012, Last Modified: 06 Sept 2012
* @description Global utility class that gives the ability to create system logs for application support.
*/
public class SystemEventLogDML{
  
  /**
  * @author Original: Jesfer Baculod (502068421) Cloud Sherpas/GEHC
  * @date Original: 27 Aug 2012, Last Modified: 06 Sept 2012
  * @description Helper Method that creates a system event log on every unhandled exceptions found while running a certain class/method
  * @param src Class/Function that writes the system event log
  * @param msg Details of the log itself
  * @param stats  Error code/Event code/Status code that identifies the log message 
  * @param evtType Type of system event log (Error, Debug, Info)
  * @param ruser Running User
  */
  
  public System_Event_Log__c generateSysLog(string src, string msg, string stats, EventType evtType, Id ruser){
    System_Event_Log__c slog = new System_Event_Log__c();
    slog.Event_Type__c = evtType.name();
    slog.Log_Source__c = src;
    slog.Status_Code__c = stats;
    slog.OwnerId = ruser;
    slog.Message__c = msg;
    return slog;
  }
  
  public enum EventType { ERROR, DEBUG, INFO } 
  
  public list <EventType> EvtType = new EventType[]{
    EventType.ERROR, //EvtType[0]
    EventType.DEBUG, //EvtType[1]
    EventType.INFO //EvtType[2]
  };
  
}